"""SSH configuration file generation service for VM instances"""
import os
import socket
from core.config import settings


# Default SSH config template
DEFAULT_SSH_CONFIG_TEMPLATE = """# --- Start of config block ---
# SSH configuration for {vm_name}
# Generated by Sandbox Manager

Host jump-host
    HostName {host_ip}
    User {username}
    IdentityFile {private_key_filename}
    StrictHostKeyChecking no

Host {vm_name}
    HostName {vm_hostname}
    User {username}
    ProxyJump jump-host
    IdentityFile {private_key_filename}
    StrictHostKeyChecking no
# --- End of config block ---
"""


def auto_detect_host_ip():
    """Auto-detect the host machine's IP address on the local network."""
    try:
        # Create a UDP socket to determine the host IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # Connect to a non-routable address (doesn't actually send data)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        # Fallback to localhost
        return "127.0.0.1"


def create_ssh_config_files(vm_name: str, ssh_keys: dict, username: str, vm_ip: str = None,
                            ssh_template: str = None, base_path: str = "_instances"):
    """
    Create SSH config files for a VM instance.

    Args:
        vm_name: Name of the VM instance
        ssh_keys: Dictionary containing 'private_key' and 'public_key'
        username: Username for SSH access
        vm_ip: VM's IP address (optional, will try to use .local if not available)
        ssh_template: Custom SSH config template (optional)
        base_path: Base directory for storing config files
    """
    # Import safe path function to prevent path traversal
    from services.ssh_key_service import _safe_instance_path
    
    # Safely resolve path
    instance_dir = _safe_instance_path(vm_name, base_path)
    instance_dir.mkdir(parents=True, exist_ok=True)
    
    # Get host IP from settings or auto-detect
    host_ip = settings.HOST_SERVER_IP
    if not host_ip:
        # Auto-detect if not configured
        host_ip = auto_detect_host_ip()
    
    # Private key filename
    private_key_filename = f"id_ed25519"
    
    # Use VM IP if available, otherwise use .local domain
    vm_hostname = vm_ip if vm_ip else f"{vm_name}.local"

    # Use provided templates or defaults
    ssh_config_content = ssh_template if ssh_template else DEFAULT_SSH_CONFIG_TEMPLATE

    # Replace placeholders in SSH config
    ssh_config_content = ssh_config_content.format(
        vm_name=vm_name,
        host_ip=host_ip,
        username=username,
        private_key_filename=private_key_filename,
        vm_hostname=vm_hostname
    )

    ssh_config_path = os.path.join(instance_dir, "ssh-config")
    with open(ssh_config_path, 'w') as f:
        f.write(ssh_config_content)

    # Create launch-server.bat file
    launch_batch_content = f"ssh -F ssh-config {vm_name}\n"
    launch_batch_path = os.path.join(instance_dir, "launch-server.bat")
    with open(launch_batch_path, 'w') as f:
        f.write(launch_batch_content)

    return {
        "ssh_config_path": ssh_config_path,
        "launch_batch_path": launch_batch_path,
        "instance_dir": instance_dir
    }
