"""SSH configuration file generation service for VM instances"""
import os
import socket
from core.config import settings


def auto_detect_host_ip():
    """Auto-detect the host machine's IP address on the local network."""
    try:
        # Create a UDP socket to determine the host IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # Connect to a non-routable address (doesn't actually send data)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        # Fallback to localhost
        return "127.0.0.1"


def create_ssh_config_files(vm_name: str, ssh_keys: dict, username: str, vm_ip: str = None, base_path: str = "_instances"):
    """
    Create SSH config and instructions files for a VM instance.
    
    Args:
        vm_name: Name of the VM instance
        ssh_keys: Dictionary containing 'private_key' and 'public_key'
        username: Username for SSH access
        vm_ip: VM's IP address (optional, will try to use .local if not available)
        base_path: Base directory for storing config files
    """
    instance_dir = os.path.join(base_path, vm_name)
    os.makedirs(instance_dir, exist_ok=True)
    
    # Get host IP from settings or auto-detect
    host_ip = settings.HOST_SERVER_IP
    if not host_ip:
        # Auto-detect if not configured
        host_ip = auto_detect_host_ip()
    
    # Private key filename
    private_key_filename = f"id_ed25519"
    
    # Use VM IP if available, otherwise use .local domain
    vm_hostname = vm_ip if vm_ip else f"{vm_name}.local"
    
    # Create SSH config file
    ssh_config_content = f"""# --- Start of config block ---
# SSH configuration for {vm_name}
# Generated by Sandbox Manager

Host jump-host
    HostName {host_ip}
    User {username}
    IdentityFile ~/.ssh/{private_key_filename}
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

Host {vm_name}
    HostName {vm_hostname}
    User {username}
    ProxyJump jump-host
    IdentityFile ~/.ssh/{private_key_filename}
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
# --- End of config block ---
"""
    
    ssh_config_path = os.path.join(instance_dir, "ssh-config")
    with open(ssh_config_path, 'w') as f:
        f.write(ssh_config_content)
    
    # Create instructions file
    vm_ip_note = f"IP Address: {vm_ip}" if vm_ip else "Note: VM IP address was not available. Check your LXD network."
    instructions_content = f"""Welcome to the Workshop!

Your personal environment is ready.

== SSH Access ==
You can connect to your instance using a standard SSH client with the provided key.

{vm_ip_note}

1. Save your private key
   Save your private key ({private_key_filename}) to your ~/.ssh/ directory.
   
   Examples:
   - Linux/Mac:  /home/{username}/.ssh/ or ~/.ssh/
   - Windows:    C:\\Users\\YourUsername\\.ssh\\

2. Add SSH config to your ~/.ssh/config file
   Copy the contents of the 'ssh-config' file (in this folder) and append it to:
   ~/.ssh/config
   
3. Make sure the files have proper permissions:
   chmod 600 ~/.ssh/*

4. Connect to your VM by running this command in your terminal:
   ssh {vm_name}

== Troubleshooting ==
- If you get permission denied errors, make sure the private key has correct permissions:
  chmod 600 ~/.ssh/{private_key_filename}

- Try connecting directly to the host server:
  ssh jump-host

== Security Notes ==
- Never share your private key with anyone
- Keep your private key permissions restricted (chmod 600)
- The private key is only stored locally on this machine
"""
    
    instructions_path = os.path.join(instance_dir, "instructions.txt")
    with open(instructions_path, 'w') as f:
        f.write(instructions_content)
    
    return {
        "ssh_config_path": ssh_config_path,
        "instructions_path": instructions_path,
        "instance_dir": instance_dir
    }
